Added initramfs_data.S to fix compilation error
Here is the error:
/home/krittinkalra/aarch64-linux-android-7.x/bin/aarch64-linux-android-ld.bfd: cannot find usr/initramfs_data.o: No such file or directory
make[2]: *** [usr/built-in.o] Error 1
make[1]: *** [usr] Error 2
make[1]: *** Waiting for unfinished jobs....
  LD      init/built-in.o
make[1]: *** wait: No child processes.  Stop.
make: *** [sub-make] Error 2

Turns out initramfs_data.S was missing from Agni's source. I added it to usr/ and the error got solved