Specified a custom path to fix a compilation error
The error was:
/home/krittin/JackAss-Kernel/arch/arm/boot/dts/qcom/kenzo/msm8956-kenzo.dtsi:15:10: fatal error: dt-bindings/clock/msm-clocks-8976.h: No such file or directory
 #include <dt-bindings/clock/msm-clocks-8976.h>

 #include "" searches for the file in the same directory as the file
 which is being compiled (in this case that is msm8956-kenzo.dtsi), so I
 used multiple ../ to direct the path to
 /home/krittin/JackAss-Kernel/include/dt-bindings/clock/msm-clocks-8976.h